# Usar imagem base node:14
FROM node:14

# Definir diretório de trabalho
WORKDIR /app

# Copiar package.json e instalar dependências
COPY package*.json ./
RUN npm install

# Copiar o restante do código
COPY . .

# Expor a porta 5000 para acessar o back-end
EXPOSE 5000

# Comando para iniciar o servidor
CMD ["node", "server.js"]
