name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Frontend Image
        run: |
          docker build -t myapp-frontend ./frontend
          docker tag myapp-frontend:latest ${{ secrets.DOCKER_USERNAME }}/myapp-frontend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/myapp-frontend:latest

      - name: Build and Push Backend Image
        run: |
          docker build -t myapp-backend ./backend
          docker tag myapp-backend:latest ${{ secrets.DOCKER_USERNAME }}/myapp-backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/myapp-backend:latest

      - name: Deploy to Production
        run: echo "Deploying to production environment simulated here."
